export type EvidenceFieldStatus = "NOT LOADED" | "UNKNOWN" | "NOT APPLICABLE";
export type EvidenceVerificationStatus = "NOT LOADED" | "VERIFIED" | "REJECTED";
export type EvidenceCompleteness = "NOT READY" | "PARTIAL" | "COMPLETE" | "VERIFIED";
export type EvidenceLifecycleStage = "RECEIVED" | "PARSED" | "IDENTIFIED" | "TRACEABILITY_PENDING" | "CALIBRATION_PENDING" | "UNCERTAINTY_PENDING" | "VERIFICATION_PENDING" | "VERIFIED" | "REJECTED";
export type EvidenceScientificClassification = "SIMULATION" | "DERIVED" | "MEASURED" | "UNKNOWN";

export interface EvidenceContractField {
  status: EvidenceFieldStatus;
  value?: string;
  note: string;
}

export interface LaboratoryEvidenceRecord {
  evidenceId: EvidenceContractField;
  experimentId: EvidenceContractField;
  sampleId: EvidenceContractField;
  instrumentId: EvidenceContractField;
  measurementId: EvidenceContractField;
  datasetId: EvidenceContractField;
  source: EvidenceContractField;
  sourceType: EvidenceContractField;
  receivedAt: EvidenceContractField;
  measurementTimestamp: EvidenceContractField;
  unit: EvidenceContractField;
  value: EvidenceContractField;
  uncertainty: EvidenceContractField;
  calibrationReference: EvidenceContractField;
  laboratoryReference: EvidenceContractField;
  referenceStandard: EvidenceContractField;
  provenance: EvidenceScientificClassification;
  verificationStatus: EvidenceVerificationStatus;
  interpretationLimit: string;
}

export interface EvidenceFieldDefinition {
  key: keyof Omit<LaboratoryEvidenceRecord, "provenance" | "verificationStatus" | "interpretationLimit">;
  label: string;
  interpretationLimit: string;
}

export const EVIDENCE_RECORD_FIELD_DEFINITIONS: readonly EvidenceFieldDefinition[] = [
  { key: "evidenceId", label: "Evidence ID", interpretationLimit: "No evidence identifier exists until a real evidence record is received." },
  { key: "experimentId", label: "Experiment ID", interpretationLimit: "A future association must not create an experiment or session." },
  { key: "sampleId", label: "Sample ID", interpretationLimit: "No sample identifier is generated by this UI." },
  { key: "instrumentId", label: "Instrument ID", interpretationLimit: "A registry channel is not proof of a physical instrument record." },
  { key: "measurementId", label: "Measurement ID", interpretationLimit: "No measurement identifier exists without a real measurement record." },
  { key: "datasetId", label: "Dataset ID", interpretationLimit: "No dataset identifier exists without an ingested source." },
  { key: "source", label: "Source", interpretationLimit: "Source remains unloaded until a legitimate laboratory source is supplied." },
  { key: "sourceType", label: "Source Type", interpretationLimit: "Source type is not inferred from simulation data." },
  { key: "receivedAt", label: "Received At", interpretationLimit: "No receipt timestamp is generated until evidence is actually received." },
  { key: "measurementTimestamp", label: "Measurement Timestamp", interpretationLimit: "Simulation time is not a laboratory measurement timestamp." },
  { key: "unit", label: "Unit", interpretationLimit: "A display unit does not constitute an evidence-backed measurement unit." },
  { key: "value", label: "Value", interpretationLimit: "No measurement value is created; NOT LOADED is not zero." },
  { key: "uncertainty", label: "Uncertainty", interpretationLimit: "No uncertainty value is inferred from the P19 contract." },
  { key: "calibrationReference", label: "Calibration Reference", interpretationLimit: "No calibration reference is created from P17/P18 UI contracts." },
  { key: "laboratoryReference", label: "Laboratory Reference", interpretationLimit: "No laboratory reference or competence claim is present." },
  { key: "referenceStandard", label: "Reference Standard", interpretationLimit: "No reference standard is assumed or created." },
] as const;

export const EVIDENCE_LIFECYCLE: readonly EvidenceLifecycleStage[] = [
  "RECEIVED", "PARSED", "IDENTIFIED", "TRACEABILITY_PENDING", "CALIBRATION_PENDING", "UNCERTAINTY_PENDING", "VERIFICATION_PENDING", "VERIFIED", "REJECTED",
] as const;

export const LABORATORY_EVIDENCE_RECORDS: readonly LaboratoryEvidenceRecord[] = [];

export function getEvidenceCompleteness(records: readonly LaboratoryEvidenceRecord[]): EvidenceCompleteness {
  if (records.length === 0) return "NOT READY";
  if (records.every(isEvidenceVerified)) return "VERIFIED";
  return "PARTIAL";
}

export function isEvidenceVerified(record: LaboratoryEvidenceRecord) {
  const required: readonly EvidenceContractField[] = [
    record.evidenceId, record.sampleId, record.instrumentId, record.measurementId, record.source,
    record.measurementTimestamp, record.unit, record.value, record.uncertainty,
    record.calibrationReference, record.laboratoryReference, record.referenceStandard,
  ];
  return record.verificationStatus === "VERIFIED" && record.provenance === "MEASURED" && required.every(field => field.status === "NOT APPLICABLE" ? false : typeof field.value === "string" && field.value.length > 0);
}

export function getEvidenceLifecycleStatus(records: readonly LaboratoryEvidenceRecord[], stage: EvidenceLifecycleStage): EvidenceFieldStatus | EvidenceVerificationStatus {
  if (records.length === 0) return "NOT LOADED";
  if (stage === "VERIFIED") return records.every(isEvidenceVerified) ? "VERIFIED" : "NOT LOADED";
  return "NOT LOADED";
}
