import { useMemo, useState } from "react";
import { Link } from "wouter";
import { BookOpen, BrainCircuit, ChevronRight, CircleHelp, Database, FlaskConical, GitBranch, GraduationCap, Info, Microscope, Search, ShieldAlert, Sparkles } from "lucide-react";
import { experimentGuide, faq, glossary, literacyModes, methods, overviewFlow, scientificStatus, whyThisValues, type LiteracyMode } from "@/lib/scientificKnowledge";
import { ExperimentalIdentityKnowledge } from "@/components/ExperimentalIdentityKnowledge";

const statusTone: Record<string, string> = {
  AVAILABLE: "border-emerald-500/30 bg-emerald-500/10 text-emerald-300",
  PARTIAL: "border-amber-500/30 bg-amber-500/10 text-amber-300",
  "NOT AVAILABLE": "border-slate-600 bg-slate-800/70 text-slate-300",
  "FUTURE CAPABILITY": "border-violet-500/30 bg-violet-500/10 text-violet-300",
};

function StatusBadge({ status }: { status: string }) {
  return <span className={`inline-flex rounded border px-2 py-1 font-mono text-[9px] tracking-[0.14em] ${statusTone[status] ?? statusTone["NOT AVAILABLE"]}`}>{status}</span>;
}

function Source({ children }: { children: string }) {
  return <p className="mt-3 border-t border-slate-800 pt-3 font-mono text-[9px] leading-relaxed tracking-[0.08em] text-slate-500">SOURCE / PROVENANCE: {children}</p>;
}

function SectionTitle({ icon, eyebrow, title, children }: { icon: React.ReactNode; eyebrow: string; title: string; children: React.ReactNode }) {
  return <header className="mb-5"><div className="flex items-center gap-2 font-mono text-[10px] tracking-[0.24em] text-cyan-300">{icon}{eyebrow}</div><h2 className="mt-2 text-xl font-semibold tracking-[0.06em] text-slate-100 md:text-2xl">{title}</h2><div className="mt-2 max-w-3xl text-sm leading-relaxed text-slate-400">{children}</div></header>;
}

function Field({ label, value }: { label: string; value: string }) {
  return <div className="border-l border-cyan-500/30 bg-slate-950/65 px-3 py-2"><div className="font-mono text-[9px] tracking-[0.14em] text-slate-500">{label}</div><p className="mt-1 text-xs leading-relaxed text-slate-300">{value}</p></div>;
}

export default function ScientificKnowledgeCenter() {
  const [mode, setMode] = useState<LiteracyMode>("SCIENTIFIC");
  const [query, setQuery] = useState("");
  const filteredGlossary = useMemo(() => glossary.filter(([term, definition]) => `${term} ${definition}`.toLowerCase().includes(query.toLowerCase())), [query]);
  const filteredMethods = useMemo(() => methods.filter(method => `${method.title} ${method.what} ${method.availability}`.toLowerCase().includes(query.toLowerCase())), [query]);
  const modeDescription = literacyModes[mode].description;

  return <main className="min-h-screen bg-[#020712] text-slate-100">
    <div className="min-h-screen bg-[radial-gradient(circle_at_15%_-10%,rgba(8,145,178,.22),transparent_28%),radial-gradient(circle_at_88%_4%,rgba(124,58,237,.14),transparent_25%),#020712]">
      <header className="border-b border-cyan-500/20 bg-slate-950/85 backdrop-blur"><div className="mx-auto flex max-w-[1500px] flex-col gap-4 px-4 py-5 md:px-6 lg:flex-row lg:items-center lg:justify-between"><div><div className="flex items-center gap-2 font-mono text-[10px] tracking-[0.28em] text-cyan-300"><GraduationCap className="h-4 w-4" />IUVFES // SCIENTIFIC KNOWLEDGE & METHOD CENTER</div><h1 className="mt-2 text-2xl font-semibold tracking-[0.08em] md:text-3xl">READ THE SYSTEM WITHOUT INVENTING IT</h1><p className="mt-2 max-w-3xl text-sm text-slate-400">Lapisan pendidikan dan interpretasi untuk Digital Twin, CausalFrame, evidence, provenance, material context, dan batas ilmiah IUVFES.</p></div><Link href="/"><span className="inline-flex cursor-pointer items-center gap-2 border border-cyan-500/30 px-3 py-2 font-mono text-[10px] tracking-[0.12em] text-cyan-200 transition hover:bg-cyan-500/10">CONTROL ROOM <ChevronRight className="h-3.5 w-3.5" /></span></Link></div></header>

      <div className="mx-auto grid max-w-[1500px] gap-5 px-4 py-5 md:px-6 lg:grid-cols-[235px_minmax(0,1fr)]">
        <aside className="lg:sticky lg:top-4 lg:h-fit"><nav aria-label="Knowledge Center sections" className="overflow-x-auto border border-slate-800 bg-slate-950/75 p-3 lg:overflow-visible"><div className="mb-2 font-mono text-[9px] tracking-[0.2em] text-slate-500">KNOWLEDGE MAP</div><div className="flex gap-1 lg:block lg:space-y-1">{[["overview","Overview"],["boundary","Scientific Boundary"],["methods","Methods"],["twin","Digital Twin"],["causal","CausalFrame"],["evidence","Evidence"],["provenance","Provenance"],["ai","AI Analysis"],["material","Material Knowledge"],["guide","Experiment Guide"],["glossary","Glossary"],["faq","FAQ"],["why","Why this value?"],["user-guide","User Guide"]].map(([id,label]) => <a key={id} href={`#${id}`} className="block whitespace-nowrap border border-transparent px-2 py-1.5 text-xs text-slate-400 transition hover:border-cyan-500/25 hover:bg-cyan-500/5 hover:text-cyan-200">{label}</a>)}</div></nav></aside>

        <div className="min-w-0 space-y-5">
          <section className="border border-cyan-500/20 bg-slate-950/70 p-4 md:p-6"><div className="flex flex-col gap-4 xl:flex-row xl:items-end xl:justify-between"><div><div className="font-mono text-[10px] tracking-[0.18em] text-amber-300">SCIENTIFIC LITERACY MODE</div><p className="mt-2 text-sm text-slate-400">{modeDescription} Mode ini hanya mengubah presentasi pendidikan; tidak mengubah data, state, provenance, atau evidence.</p></div><div className="flex flex-wrap gap-2" role="group" aria-label="Scientific literacy mode">{(Object.keys(literacyModes) as LiteracyMode[]).map(item => <button key={item} type="button" aria-pressed={mode === item} onClick={() => setMode(item)} className={`border px-3 py-2 font-mono text-[10px] tracking-[0.12em] ${mode === item ? "border-cyan-400 bg-cyan-400 text-slate-950" : "border-slate-700 text-slate-300 hover:border-cyan-500/40"}`}>{item}</button>)}</div></div><label className="mt-5 flex items-center gap-2 border border-slate-700 bg-slate-950 px-3 py-2 text-slate-400"><Search className="h-4 w-4 text-cyan-300" /><span className="sr-only">Search knowledge content</span><input value={query} onChange={event => setQuery(event.target.value)} className="w-full bg-transparent text-sm outline-none placeholder:text-slate-600" placeholder="Search methods, glossary, availability…" /></label></section>

          <section id="overview" className="border border-slate-800 bg-slate-950/65 p-4 md:p-6"><SectionTitle icon={<BookOpen className="h-4 w-4" />} eyebrow="IUVFES OVERVIEW" title="Scientific Digital Twin / Virtual Laboratory">IUVFES is a closed-loop causal simulation infrastructure. It visualizes engine state, records causal frames, supports replay/evidence, and keeps simulation-derived output separate from laboratory observation.</SectionTitle><div className="flex flex-wrap items-center gap-2">{overviewFlow.map((step, index) => <div key={step} className="flex items-center gap-2"><span className="border border-cyan-500/25 bg-cyan-500/5 px-2 py-1 font-mono text-[10px] text-cyan-200">{step}</span>{index < overviewFlow.length - 1 ? <ChevronRight className="h-3 w-3 text-slate-600" /> : null}</div>)}</div><div className="mt-5 grid gap-3 md:grid-cols-2"><Field label="WHAT IUVFES DOES" value="Represents closed-loop simulation state, causal relationships, visual process state, replay, provenance, and simulation evidence when existing contracts provide them." /><Field label="WHAT IUVFES DOES NOT DO" value="It does not convert simulation output, AI interpretation, or missing values into laboratory proof." /></div><Source>docs/BUKU_BESAR_IUVFES_DIGITAL_TWIN.md</Source></section>

          <section id="boundary" className="border border-amber-500/25 bg-amber-500/[0.045] p-4 md:p-6"><SectionTitle icon={<ShieldAlert className="h-4 w-4 text-amber-300" />} eyebrow="SCIENTIFIC STATUS & BOUNDARY" title="Classification must survive explanation">`KNOWN` is not automatically laboratory-validated. P14 presents status labels as a boundary, not as a confidence score.</SectionTitle><div className="grid gap-2 md:grid-cols-2">{scientificStatus.map(([label, explanation]) => <div key={label} className="border border-amber-500/15 bg-slate-950/60 p-3"><div className="font-mono text-[10px] tracking-[0.16em] text-amber-200">{label}</div><p className="mt-1 text-xs leading-relaxed text-slate-400">{explanation}</p></div>)}</div><div className="mt-4 border-l-2 border-amber-400 bg-slate-950/65 p-3 text-sm leading-relaxed text-slate-300"><b>RESULT A — TESTED / EVIDENCED</b>, <b>RESULT B — ESTIMATED / POSSIBLE</b>, and <b>RESULT C — AI ANALYSIS</b> must remain distinct. P14 does not promote Result B/C to Result A.</div><Source>docs/CONTROL_ROOM_NEXT_WORK_ORDER.md; docs/BUKU_BESAR_IUVFES_DIGITAL_TWIN.md</Source></section>

          <section id="methods" className="border border-slate-800 bg-slate-950/65 p-4 md:p-6"><SectionTitle icon={<Microscope className="h-4 w-4" />} eyebrow="SCIENTIFIC METHOD" title="Available methods and explicit limitations">Every method uses WHAT, WHY, INPUT, PROCESS, OUTPUT, LIMITATION, EVIDENCE REQUIREMENT, and SOURCE / PROVENANCE. Availability reflects the audited current implementation.</SectionTitle><div className="space-y-3">{filteredMethods.map(method => <details key={method.id} className="group border border-slate-800 bg-slate-950/70 open:border-cyan-500/30"><summary className="flex cursor-pointer list-none items-center justify-between gap-3 p-4"><div><h3 className="text-sm font-semibold text-slate-200">{method.title}</h3><p className="mt-1 text-xs text-slate-500">{method.what}</p></div><StatusBadge status={method.availability} /></summary><div className="grid gap-2 border-t border-slate-800 p-4 md:grid-cols-2"><Field label="WHAT" value={method.what} /><Field label="WHY" value={method.why} /><Field label="INPUT" value={method.input} /><Field label="PROCESS" value={method.process} /><Field label="OUTPUT" value={method.output} /><Field label="LIMITATION" value={method.limitation} /><Field label="EVIDENCE REQUIREMENT" value={method.evidenceRequirement} /><Field label="SOURCE / PROVENANCE" value={method.source} /></div></details>)}{filteredMethods.length === 0 ? <p className="py-4 text-sm text-slate-500">No method matches the current search. No content is inferred.</p> : null}</div></section>

          <section id="twin" className="grid gap-4 border border-slate-800 bg-slate-950/65 p-4 md:grid-cols-2 md:p-6"><div><SectionTitle icon={<Sparkles className="h-4 w-4" />} eyebrow="DIGITAL TWIN" title="Engine state before visual state">The 3D twin is a presentation of active CausalFrame state. It does not calculate a second physics model, generate hidden telemetry, or become scientific truth by being visually convincing.</SectionTitle><Source>docs/PROCESS_SIMULATOR_DATA_FLOW.md</Source></div><div id="causal" className="border border-cyan-500/20 bg-cyan-500/[0.035] p-4"><div className="font-mono text-[10px] tracking-[0.18em] text-cyan-300">CAUSALFRAME</div><p className="mt-2 text-sm leading-relaxed text-slate-300">An authoritative process-state representation for one causal step. Existing surfaces can use it for 3D, trends, causal inspection, replay, recorder, and evidence when their contracts support it.</p><div className="mt-3 font-mono text-[10px] leading-relaxed text-slate-500">sensor before → controller/interlock → intended command → effective command → physical response → observed sensor after → safety/result</div><Source>docs/BUKU_BESAR_IUVFES_DIGITAL_TWIN.md; docs/PROCESS_SIMULATOR_DATA_FLOW.md</Source></div></section>

          <section id="evidence" className="grid gap-4 border border-slate-800 bg-slate-950/65 p-4 md:grid-cols-2 md:p-6"><div><SectionTitle icon={<Database className="h-4 w-4" />} eyebrow="EVIDENCE" title="Traceable does not mean laboratory-proven">Evidence can package existing CausalFrame/replay information with identity and provenance. A simulation-derived package is not automatically experimental proof.</SectionTitle><Source>docs/BUKU_BESAR_IUVFES_DIGITAL_TWIN.md; ScientificRunRecorder</Source></div><div id="provenance" className="border border-emerald-500/20 bg-emerald-500/[0.035] p-4"><div className="font-mono text-[10px] tracking-[0.18em] text-emerald-300">PROVENANCE</div><p className="mt-2 text-sm leading-relaxed text-slate-300">Use source labels to distinguish MEASURED, SIMULATION / DERIVED, ASSUMED, DATASHEET_REQUIRED, UNKNOWN / DATA GAP, and VALIDATED. A source reference is not a replacement for an evidence chain.</p><Source>docs/PROCESS_SIMULATOR_DATA_FLOW.md</Source></div></section>

          <ExperimentalIdentityKnowledge mode={mode} />
          <section id="ai" className="border border-violet-500/25 bg-violet-500/[0.04] p-4 md:p-6"><SectionTitle icon={<BrainCircuit className="h-4 w-4 text-violet-300" />} eyebrow="AI ANALYSIS" title="Interpretation remains separate from proof">AI may be described as a potential pattern/correlation/conflict/knowledge-gap/hypothesis aid. The audited current user-facing AI-analysis contract is <b>NOT AVAILABLE</b>, so P14 displays no AI-generated result, recommendation, confidence, or scientific claim.</SectionTitle><div className="grid gap-2 md:grid-cols-2"><Field label="ALLOWED EXPLANATION" value="AI analysis is not experimental proof and cannot validate simulation without appropriate laboratory evidence." /><Field label="CURRENT RUNTIME AVAILABILITY" value="NOT AVAILABLE — P14 does not invent an AI result or recommendation." /></div><Source>P14 source audit</Source></section>

          <section id="material" className="border border-slate-800 bg-slate-950/65 p-4 md:p-6"><SectionTitle icon={<FlaskConical className="h-4 w-4" />} eyebrow="MATERIAL KNOWLEDGE" title="Sample identity is more than a material name">P14 lists the fields that the current intake actually captures and marks unconfirmed context as NOT AVAILABLE rather than filling it from inference.</SectionTitle><div className="grid gap-2 md:grid-cols-2"><Field label="CAPTURED / OPERATOR-OPTIONAL" value="Material, origin, batch, harvest date, particle size, pre-treatment, mass, water content, oil content, researcher and baseline process inputs." /><Field label="NOT CONFIRMED BY CURRENT INTAKE" value="Species/variety, plant part, fresh/dry/frozen state, drying/freezing history, altitude, cultivation/fertilizer/treatment, storage, solvent, and full extraction protocol." /></div><p className="mt-4 text-sm leading-relaxed text-slate-400">Samples with the same material name are not automatically equivalent. P14 never merges sample identity or creates missing material context.</p><Source>client/src/components/ScientificExperimentIntake.tsx</Source></section>

          <section id="guide" className="border border-slate-800 bg-slate-950/65 p-4 md:p-6"><SectionTitle icon={<GitBranch className="h-4 w-4" />} eyebrow="EXPERIMENT GUIDE" title="Use only steps supported by the current system">Availability labels distinguish current implementation from future work. P14 does not create an experiment or session.</SectionTitle><ol className="space-y-2">{experimentGuide.map(([step, status, description], index) => <li key={step} className="grid gap-2 border border-slate-800 bg-slate-950/70 p-3 md:grid-cols-[32px_1fr_auto]"><span className="grid h-7 w-7 place-items-center border border-cyan-500/25 font-mono text-xs text-cyan-200">{index + 1}</span><div><div className="text-sm font-medium text-slate-200">{step}</div><p className="mt-1 text-xs leading-relaxed text-slate-500">{description}</p></div><StatusBadge status={status} /></li>)}</ol></section>

          <section id="glossary" className="border border-slate-800 bg-slate-950/65 p-4 md:p-6"><SectionTitle icon={<Info className="h-4 w-4" />} eyebrow="GLOSSARY" title="Shared vocabulary">Filter uses the same search field above. Definitions remain educational and do not alter live data.</SectionTitle><div className="grid gap-2 md:grid-cols-2">{filteredGlossary.map(([term, definition]) => <div key={term} className="border border-slate-800 bg-slate-950/70 p-3"><div className="font-mono text-[10px] tracking-[0.14em] text-cyan-200">{term}</div><p className="mt-1 text-xs leading-relaxed text-slate-400">{definition}</p></div>)}{filteredGlossary.length === 0 ? <p className="text-sm text-slate-500">No glossary term matches the current search.</p> : null}</div></section>

          <section id="faq" className="border border-slate-800 bg-slate-950/65 p-4 md:p-6"><SectionTitle icon={<CircleHelp className="h-4 w-4" />} eyebrow="FAQ" title="Questions that protect the boundary">Critical scientific boundary text remains visible in the page; it is not hidden in a tooltip.</SectionTitle><div className="space-y-2">{faq.map(([question, answer]) => <details key={question} className="border border-slate-800 bg-slate-950/70 p-3"><summary className="cursor-pointer text-sm font-medium text-slate-200">{question}</summary><p className="mt-3 text-sm leading-relaxed text-slate-400">{answer}</p></details>)}</div></section>

          <section id="why" className="border border-cyan-500/25 bg-cyan-500/[0.035] p-4 md:p-6"><SectionTitle icon={<Info className="h-4 w-4 text-cyan-300" />} eyebrow="WHY AM I SEEING THIS?" title="Runtime field explanation pattern">These cards explain fields that existing Control Room surfaces can expose. They are documentation examples, not live runtime values.</SectionTitle><div className="grid gap-3 md:grid-cols-2">{whyThisValues.map(item => <article key={item.label} className="border border-cyan-500/15 bg-slate-950/80 p-4"><h3 className="font-mono text-xs tracking-[0.12em] text-cyan-200">{item.label}</h3><div className="mt-3 space-y-2"><Field label="SOURCE" value={item.source} /><Field label="FIELD" value={item.field} /><Field label="CLASSIFICATION" value={item.classification} /><Field label="VISUAL MEANING" value={item.meaning} /><Field label="THIS VALUE DOES NOT REPRESENT" value={item.notMeaning} /></div></article>)}</div><Source>docs/PROCESS_SIMULATOR_DATA_FLOW.md</Source></section>

          <section id="user-guide" className="border border-slate-800 bg-slate-950/65 p-4 md:p-6"><SectionTitle icon={<GraduationCap className="h-4 w-4" />} eyebrow="USER GUIDE" title="Read, classify, then operate">First read the scientific boundary and method availability. Then use Control Room only with a valid operator session. Inspect provenance before interpreting a result, and treat NOT AVAILABLE/UNKNOWN as an actionable limit rather than empty decoration.</SectionTitle><div className="border-l-2 border-amber-400 bg-amber-500/[0.05] p-4 text-sm leading-relaxed text-slate-300">P10 remains <b>AUTH BLOCKED</b>. This Knowledge Center is available for literacy and documentation; it does not bypass authentication, create a session, or change the P10 acceptance gate.</div></section>
        </div>
      </div>
    </div>
  </main>;
}
