import { z } from "zod";
import { protectedProcedure, router } from "./_core/trpc";
import { TRPCError } from "@trpc/server";
import * as db from "./db";
import { ClosedLoopSimulationEngine, type ClosedLoopSimulationConfig } from "./closedLoopSimulation";
import { describeClosedLoopEngineContract } from "./closedLoopInputContract";
import { mapExperimentInputsToEngine, getClosedLoopWiringReport } from "./closedLoopWiring";
import { recordClosedLoopRun } from "./scientificEventJournal";
import { persistSimulationDataset } from "./scientificDatasetPersistence";
import { saveClosedLoopSession } from "./closedLoopSessionStore";
import { createRuntimeSession, getRuntimeFrames, getRuntimeSession, getRuntimeSnapshot, pauseRuntimeSession, resetRuntimeSession, resumeRuntimeSession, startRuntimeSession, stepRuntimeSession, stopRuntimeSession } from "./closedLoopRuntimeStore";

const inputSchema = z.object({ experimentId: z.string().min(1), materialWeight: z.number().min(0.1).max(1000), waterContent: z.number().min(0).max(100), oilContent: z.number().min(0).max(100), targetPressure: z.number().min(1).max(1000), targetTemperature: z.number().min(20).max(150), coolingTemperature: z.number().min(25).max(80).default(35), dtSeconds: z.number().min(0.1).max(10).default(1), maxSteps: z.number().int().min(1).max(100000).default(10000) });
const controlSchema = z.object({ sessionId: z.string().min(1), targetPressureMbar: z.number().min(1).max(1000).optional(), targetTemperatureC: z.number().min(25).max(150).optional(), coolingTemperatureC: z.number().min(25).max(80).optional(), heaterMax: z.number().min(0).max(1).optional(), vacuumPumpMax: z.number().min(0).max(1).optional(), condenserMax: z.number().min(0).max(1).optional(), coolingMax: z.number().min(0).max(1).optional(), operatorNotes: z.string().max(500).optional() });
function toEngineConfig(input: z.infer<typeof inputSchema>): ClosedLoopSimulationConfig { return mapExperimentInputsToEngine(input); }
async function assertExperimentAccess(ctx: { user?: { id: number; role: string } | null }, experimentId: string) { if (!ctx.user) throw new TRPCError({ code: "UNAUTHORIZED" }); const experiment = await db.getExperiment(experimentId); if (!experiment) throw new TRPCError({ code: "NOT_FOUND" }); if (experiment.userId !== ctx.user.id && ctx.user.role !== "admin") throw new TRPCError({ code: "FORBIDDEN" }); return experiment; }
async function persistRuntime(sessionId: string) { const session = getRuntimeSession(sessionId); await saveClosedLoopSession(session.experimentId, session.status === "running" ? "running" : session.status === "paused" ? "paused" : session.status === "completed" ? "completed" : session.status === "failed" ? "failed" : "stopped", session.engine.getSnapshot()); }
function sessionView(sessionId: string) { const session = getRuntimeSession(sessionId); const snapshot = getRuntimeSnapshot(sessionId); return { sessionId: session.sessionId, experimentId: session.experimentId, status: session.status, createdAt: session.createdAt, startedAt: session.startedAt ?? null, updatedAt: session.updatedAt, configuration: session.configuration, dataSource: describeClosedLoopEngineContract(), wiring: getClosedLoopWiringReport(), currentStep: snapshot.stepNumber, elapsedSeconds: snapshot.elapsedSeconds, currentFrame: snapshot.frames.at(-1) ?? null, frameCount: snapshot.frames.length, pausedSteps: snapshot.pausedSteps, targets: snapshot.targets, operatorLimits: snapshot.control.operatorLimits }; }

export const closedLoopRouter = router({
  create: protectedProcedure.input(inputSchema).mutation(async ({ ctx, input }) => { await assertExperimentAccess(ctx, input.experimentId); const session = createRuntimeSession(input.experimentId, toEngineConfig(input)); await persistRuntime(session.sessionId); return sessionView(session.sessionId); }),
  start: protectedProcedure.input(z.string().min(1)).mutation(async ({ ctx, input }) => { const session = getRuntimeSession(input); await assertExperimentAccess(ctx, session.experimentId); startRuntimeSession(input); await db.updateExperimentStatus(session.experimentId, "running"); await db.logControlAction({ experimentId: session.experimentId, action: "start", operatorNotes: "Closed-loop Control Room started." }); await persistRuntime(input); return sessionView(input); }),
  step: protectedProcedure.input(z.string().min(1)).mutation(async ({ ctx, input }) => { const session = getRuntimeSession(input); await assertExperimentAccess(ctx, session.experimentId); const frame = stepRuntimeSession(input); await persistRuntime(input); return { frame, session: sessionView(input) }; }),
  control: protectedProcedure.input(controlSchema).mutation(async ({ ctx, input }) => { const session = getRuntimeSession(input.sessionId); await assertExperimentAccess(ctx, session.experimentId); const beforeTargets = session.engine.getTargets(); const beforeLimits = session.engine.getOperatorLimits(); session.engine.setTargets({ targetPressureMbar: input.targetPressureMbar, targetTemperatureC: input.targetTemperatureC, coolingTemperatureC: input.coolingTemperatureC }); session.engine.setOperatorLimits({ heaterMax: input.heaterMax, vacuumPumpMax: input.vacuumPumpMax, condenserMax: input.condenserMax, coolingMax: input.coolingMax }); const afterTargets = session.engine.getTargets(); const afterLimits = session.engine.getOperatorLimits(); const changes: Array<[string, number, number]> = []; if (beforeTargets.targetPressureMbar !== afterTargets.targetPressureMbar) changes.push(["targetPressureMbar", beforeTargets.targetPressureMbar, afterTargets.targetPressureMbar]); if (beforeTargets.targetTemperatureC !== afterTargets.targetTemperatureC) changes.push(["targetTemperatureC", beforeTargets.targetTemperatureC, afterTargets.targetTemperatureC]); if (beforeTargets.coolingTemperatureC !== afterTargets.coolingTemperatureC) changes.push(["coolingTemperatureC", beforeTargets.coolingTemperatureC, afterTargets.coolingTemperatureC]); if (beforeLimits.heaterMax !== afterLimits.heaterMax) changes.push(["heaterMax", beforeLimits.heaterMax, afterLimits.heaterMax]); if (beforeLimits.vacuumPumpMax !== afterLimits.vacuumPumpMax) changes.push(["vacuumPumpMax", beforeLimits.vacuumPumpMax, afterLimits.vacuumPumpMax]); if (beforeLimits.condenserMax !== afterLimits.condenserMax) changes.push(["condenserMax", beforeLimits.condenserMax, afterLimits.condenserMax]); if (beforeLimits.coolingMax !== afterLimits.coolingMax) changes.push(["coolingMax", beforeLimits.coolingMax, afterLimits.coolingMax]); for (const [parameterName, oldValue, newValue] of changes) await db.logControlAction({ experimentId: session.experimentId, action: "parameter_change", parameterName, oldValue: String(oldValue), newValue: String(newValue), operatorNotes: input.operatorNotes }); await persistRuntime(input.sessionId); return sessionView(input.sessionId); }),
  pause: protectedProcedure.input(z.string().min(1)).mutation(async ({ ctx, input }) => { const session = getRuntimeSession(input); await assertExperimentAccess(ctx, session.experimentId); pauseRuntimeSession(input); await db.updateExperimentStatus(session.experimentId, "paused"); await db.logControlAction({ experimentId: session.experimentId, action: "pause", operatorNotes: "Closed-loop Control Room paused." }); await persistRuntime(input); return sessionView(input); }),
  resume: protectedProcedure.input(z.string().min(1)).mutation(async ({ ctx, input }) => { const session = getRuntimeSession(input); await assertExperimentAccess(ctx, session.experimentId); resumeRuntimeSession(input); await db.updateExperimentStatus(session.experimentId, "running"); await db.logControlAction({ experimentId: session.experimentId, action: "resume", operatorNotes: "Closed-loop Control Room resumed." }); await persistRuntime(input); return sessionView(input); }),
  stop: protectedProcedure.input(z.string().min(1)).mutation(async ({ ctx, input }) => { const session = getRuntimeSession(input); await assertExperimentAccess(ctx, session.experimentId); stopRuntimeSession(input); await db.updateExperimentStatus(session.experimentId, "stopped"); await db.logControlAction({ experimentId: session.experimentId, action: "stop", operatorNotes: "Closed-loop Control Room stopped." }); await persistRuntime(input); return sessionView(input); }),
  reset: protectedProcedure.input(z.string().min(1)).mutation(async ({ ctx, input }) => { const session = getRuntimeSession(input); await assertExperimentAccess(ctx, session.experimentId); resetRuntimeSession(input); await db.updateExperimentStatus(session.experimentId, "draft"); await persistRuntime(input); return sessionView(input); }),
  get: protectedProcedure.input(z.string().min(1)).query(async ({ ctx, input }) => { const session = getRuntimeSession(input); await assertExperimentAccess(ctx, session.experimentId); return sessionView(input); }),
  frames: protectedProcedure.input(z.string().min(1)).query(async ({ ctx, input }) => { const session = getRuntimeSession(input); await assertExperimentAccess(ctx, session.experimentId); return { sessionId: input, frames: getRuntimeFrames(input), dataSource: describeClosedLoopEngineContract(), wiring: getClosedLoopWiringReport() }; }),
  snapshot: protectedProcedure.input(z.string().min(1)).query(async ({ ctx, input }) => { const session = getRuntimeSession(input); await assertExperimentAccess(ctx, session.experimentId); return getRuntimeSnapshot(input); }),
  run: protectedProcedure.input(inputSchema).mutation(async ({ ctx, input }) => { await assertExperimentAccess(ctx, input.experimentId); const engine = new ClosedLoopSimulationEngine(toEngineConfig(input)); await db.updateExperimentStatus(input.experimentId, "running"); const result = engine.runToCompletion(); const isComplete = result.status === "COMPLETE"; const isFault = result.status === "FAULT"; const events = await recordClosedLoopRun(input.experimentId, result); const dataset = await persistSimulationDataset({ experimentId: input.experimentId, parameters: { materialWeightKg: input.materialWeight, waterContentPercent: input.waterContent, oilContentPercent: input.oilContent, targetPressureMbar: input.targetPressure, targetTemperatureC: input.targetTemperature, dtSeconds: input.dtSeconds, maxSteps: input.maxSteps }, result, events }); const resultId = await db.createSimulationResult({ experimentId: input.experimentId, finalYield: result.finalSensors.yieldPercent, oilComposition: null, energyConsumed: result.finalSensors.energyKwh, efficiency: null, wasteComposition: null, realTimeData: result.frames, massBalance: { materialWeightKg: input.materialWeight, waterRemovedKg: result.finalSensors.waterRemovedKg, oilRecoveredKg: result.finalSensors.oilRecoveredKg }, energyBalance: { energyKwh: result.finalSensors.energyKwh } }); await db.updateExperimentStatus(input.experimentId, isComplete ? "completed" : isFault ? "failed" : "running"); return { success: isComplete, resultId, status: result.status, eventCount: events.length, lastEventHash: events.at(-1)?.eventHash ?? null, datasetId: dataset.datasetId, datasetSha256: dataset.sha256, provenanceId: dataset.provenanceId, datasetQualityStatus: dataset.qualityStatus, dataSource: describeClosedLoopEngineContract(), wiring: getClosedLoopWiringReport(), frames: result.frames, finalSensors: result.finalSensors }; }),
});