/** Reduced-order cold-trap thermal load/capacity model; not a multicomponent VLE model. */
export interface ColdTrapStageInput { temperatureC:number; volumeL:number; heatTransferAreaM2:number; condensateCapacityKg:number; }
export interface ColdTrapLoadInput { streamTemperatureC:number; dtSeconds:number; incomingCondensableKg:number; overallHeatTransferCoefficientWPerM2K?:number; latentHeatKJPerKg?:number; }
export interface ColdTrapLoadResult { heatRemovalKW:number; thermalCapacityKgPerSecond:number; condensedKg:number; remainingIncomingKg:number; capacityRemainingKg:number; effectiveness:number; status:'REDUCED_ORDER_THERMAL_LIMIT'|'DATA_GAP'|'INVALID_INPUT'; warnings:string[]; }
export function calculateColdTrapLoad(stage:ColdTrapStageInput,input:ColdTrapLoadInput):ColdTrapLoadResult {
 const U=input.overallHeatTransferCoefficientWPerM2K??0,Lh=input.latentHeatKJPerKg??2257,dt=Math.max(0,input.dtSeconds),dT=Math.max(0,input.streamTemperatureC-stage.temperatureC),warnings:string[]=[];
 if(![stage.temperatureC,stage.volumeL,stage.heatTransferAreaM2,stage.condensateCapacityKg,input.streamTemperatureC,input.dtSeconds,input.incomingCondensableKg,U,Lh].every(Number.isFinite)||stage.volumeL<0||stage.heatTransferAreaM2<0||stage.condensateCapacityKg<0||input.incomingCondensableKg<0||U<0||Lh<=0)return {heatRemovalKW:0,thermalCapacityKgPerSecond:0,condensedKg:0,remainingIncomingKg:Math.max(0,input.incomingCondensableKg),capacityRemainingKg:Math.max(0,stage.condensateCapacityKg),effectiveness:0,status:'INVALID_INPUT',warnings:['Cold-trap thermal input is invalid.']};
 if(U===0||stage.heatTransferAreaM2===0)return {heatRemovalKW:0,thermalCapacityKgPerSecond:0,condensedKg:0,remainingIncomingKg:input.incomingCondensableKg,capacityRemainingKg:stage.condensateCapacityKg,effectiveness:0,status:'DATA_GAP',warnings:['Overall heat-transfer coefficient and/or heat-transfer area is not available.']};
 const heatRemovalKW=U*stage.heatTransferAreaM2*dT/1000,thermalCapacityKgPerSecond=heatRemovalKW/Lh,condensedKg=Math.min(input.incomingCondensableKg,stage.condensateCapacityKg,thermalCapacityKgPerSecond*dt),remainingIncomingKg=Math.max(0,input.incomingCondensableKg-condensedKg),capacityRemainingKg=Math.max(0,stage.condensateCapacityKg-condensedKg),effectiveness=input.incomingCondensableKg<=0?0:condensedKg/input.incomingCondensableKg;
 if(stage.condensateCapacityKg<=condensedKg&&input.incomingCondensableKg>condensedKg)warnings.push('Cold-trap condensate inventory capacity reached during this step.');
 return {heatRemovalKW,thermalCapacityKgPerSecond,condensedKg,remainingIncomingKg,capacityRemainingKg,effectiveness,status:'REDUCED_ORDER_THERMAL_LIMIT',warnings};
}
