import { useEffect, useRef } from "react";
import * as THREE from "three";
import type { ProcessStage } from "../../../server/processStateEngine";

interface ColdTrapView { temperatureC?: number; condensedWaterKg?: number; }
interface MachineState3D { stage: ProcessStage; commands: { vacuumPump: boolean; heater: boolean; extractor: boolean; condenser: boolean; cooling: boolean }; sensors: { pressureMbar: number; temperatureC: number }; interlocks: { vacuumAchieved: boolean; overTemperature: boolean }; coldTraps?: ColdTrapView[]; }
interface Props { machine?: MachineState3D; }
function tubeBetween(curve: THREE.Curve<THREE.Vector3>, radius: number, material: THREE.MeshBasicMaterial) { return new THREE.Mesh(new THREE.TubeGeometry(curve, 32, radius, 12, false), material); }

export function ProcessMachine3D({ machine }: Props) {
  const mountRef = useRef<HTMLDivElement | null>(null); const stateRef = useRef(machine); stateRef.current = machine;
  useEffect(() => {
    const mount = mountRef.current; if (!mount) return;
    const scene = new THREE.Scene(); scene.background = new THREE.Color(0x020712);
    const camera = new THREE.PerspectiveCamera(40, 1, 0.1, 100); camera.position.set(10, 6.5, 15); camera.lookAt(0, 0.8, 0);
    const renderer = new THREE.WebGLRenderer({ antialias: true, alpha: true }); renderer.setPixelRatio(Math.min(window.devicePixelRatio, 2)); renderer.setSize(mount.clientWidth, mount.clientHeight); mount.appendChild(renderer.domElement);
    scene.add(new THREE.HemisphereLight(0x9ee7ff, 0x07111f, 1.5)); const key = new THREE.PointLight(0x22d3ee, 18, 30); key.position.set(-2, 8, 7); scene.add(key); const fill = new THREE.PointLight(0x2563eb, 8, 25); fill.position.set(5, 3, -5); scene.add(fill);
    const floor = new THREE.Mesh(new THREE.CircleGeometry(9, 64), new THREE.MeshBasicMaterial({ color: 0x06101c, transparent: true, opacity: 0.92 })); floor.rotation.x = -Math.PI / 2; floor.position.y = -2.05; scene.add(floor);

    const reactor = new THREE.Group(); reactor.position.set(-3.9, 0.7, 0); scene.add(reactor);
    const body = new THREE.Mesh(new THREE.CylinderGeometry(1.65, 1.65, 4.7, 48), new THREE.MeshStandardMaterial({ color: 0x18283b, metalness: 0.82, roughness: 0.2 })); reactor.add(body);
    const chamber = new THREE.Mesh(new THREE.CylinderGeometry(1.25, 1.25, 3.8, 48), new THREE.MeshStandardMaterial({ color: 0x0a1726, metalness: 0.25, roughness: 0.12, transparent: true, opacity: 0.56, emissive: 0x07334a })); reactor.add(chamber);
    const top = new THREE.Mesh(new THREE.CylinderGeometry(1.72, 1.72, 0.28, 48), new THREE.MeshStandardMaterial({ color: 0x25374c, metalness: 0.9, roughness: 0.18 })); top.position.y = 2.38; reactor.add(top); const bottom = top.clone(); bottom.position.y = -2.38; reactor.add(bottom);
    const heaterRing = new THREE.Mesh(new THREE.TorusGeometry(1.48, 0.085, 12, 48), new THREE.MeshBasicMaterial({ color: 0x334155 })); heaterRing.rotation.x = Math.PI / 2; heaterRing.position.y = 1.05; reactor.add(heaterRing);
    const ultrasonic = new THREE.Mesh(new THREE.CylinderGeometry(0.22, 0.22, 0.5, 24), new THREE.MeshBasicMaterial({ color: 0x334155 })); ultrasonic.position.y = -1.65; reactor.add(ultrasonic);

    const pump = new THREE.Group(); pump.position.set(4.65, -0.5, 1.6); scene.add(pump); const pumpBody = new THREE.Mesh(new THREE.BoxGeometry(2.2, 1.45, 1.5), new THREE.MeshStandardMaterial({ color: 0x172033, metalness: 0.86, roughness: 0.24 })); pump.add(pumpBody); const pumpRotor = new THREE.Mesh(new THREE.CylinderGeometry(0.42, 0.42, 0.16, 32), new THREE.MeshBasicMaterial({ color: 0x334155 })); pumpRotor.rotation.z = Math.PI / 2; pumpRotor.position.x = -1.05; pump.add(pumpRotor);

    const trapGroups: THREE.Group[] = []; const trapBodies: Array<THREE.Mesh<THREE.CylinderGeometry, THREE.MeshStandardMaterial>> = []; const trapCoils: Array<THREE.Mesh<THREE.TorusGeometry, THREE.MeshBasicMaterial>> = [];
    for (let i = 0; i < 4; i++) { const group = new THREE.Group(); group.position.set(-1.6 + i * 2.35, 3.25, -1.45); scene.add(group); trapGroups.push(group); const shell = new THREE.Mesh(new THREE.CylinderGeometry(0.7, 0.7, 1.9, 32), new THREE.MeshStandardMaterial({ color: 0x15243a, metalness: 0.72, roughness: 0.24, transparent: true, opacity: 0.8, emissive: 0x061522 })); group.add(shell); trapBodies.push(shell); const coil = new THREE.Mesh(new THREE.TorusGeometry(0.45, 0.065, 10, 32), new THREE.MeshBasicMaterial({ color: 0x2563eb })); coil.rotation.x = Math.PI / 2; coil.position.y = -0.15; group.add(coil); trapCoils.push(coil); const base = new THREE.Mesh(new THREE.CylinderGeometry(0.78, 0.78, 0.12, 32), new THREE.MeshStandardMaterial({ color: 0x203149, metalness: 0.85, roughness: 0.2 })); base.position.y = -1.02; group.add(base); }

    const vacuumLineMaterial = new THREE.MeshBasicMaterial({ color: 0x164e63 }); const vaporLineMaterial = new THREE.MeshBasicMaterial({ color: 0x155e75 }); const coolingLineMaterial = new THREE.MeshBasicMaterial({ color: 0x1e3a5f }); const powerCableMaterial = new THREE.MeshBasicMaterial({ color: 0x334155 });
    const vacuumCurve = new THREE.CatmullRomCurve3([new THREE.Vector3(-2.2, 0.2, 0.6), new THREE.Vector3(0.0, 0.2, 0.6), new THREE.Vector3(2.4, -0.05, 1.25), new THREE.Vector3(3.55, -0.35, 1.55)]);
    const vaporCurve = new THREE.CatmullRomCurve3([new THREE.Vector3(-2.7, 2.5, 0.0), new THREE.Vector3(-0.7, 2.5, 0.0), new THREE.Vector3(0.4, 3.0, -0.9), new THREE.Vector3(5.2, 3.0, -1.45)]);
    const coolingCurve = new THREE.CatmullRomCurve3([new THREE.Vector3(4.4, 1.6, -1.45), new THREE.Vector3(2.7, 1.6, -2.3), new THREE.Vector3(0.0, 1.7, -2.3), new THREE.Vector3(-2.0, 1.25, -0.8)]);
    const powerCurve = new THREE.CatmullRomCurve3([new THREE.Vector3(5.7, -1.25, 2.6), new THREE.Vector3(4.5, -1.0, 2.6), new THREE.Vector3(2.0, 0.0, 1.9), new THREE.Vector3(-1.0, 0.2, 0.8), new THREE.Vector3(-3.4, 0.2, 0.0)]);
    scene.add(tubeBetween(vacuumCurve, 0.095, vacuumLineMaterial), tubeBetween(vaporCurve, 0.085, vaporLineMaterial), tubeBetween(coolingCurve, 0.07, coolingLineMaterial), tubeBetween(powerCurve, 0.035, powerCableMaterial));
    const flowParticles = new THREE.Group(); scene.add(flowParticles); for (let i = 0; i < 20; i++) { const p = new THREE.Mesh(new THREE.SphereGeometry(0.045, 8, 8), new THREE.MeshBasicMaterial({ color: 0x67e8f9 })); p.userData.offset = i / 20; flowParticles.add(p); }
    const chamberParticles = new THREE.Group(); scene.add(chamberParticles); for (let i = 0; i < 36; i++) { const p = new THREE.Mesh(new THREE.SphereGeometry(0.035, 8, 8), new THREE.MeshBasicMaterial({ color: 0x67e8f9 })); p.userData.offset = i / 36; chamberParticles.add(p); }
    let frame = 0; let raf = 0; const resize = () => { if (!mount) return; camera.aspect = mount.clientWidth / Math.max(mount.clientHeight, 1); camera.updateProjectionMatrix(); renderer.setSize(mount.clientWidth, mount.clientHeight); }; window.addEventListener("resize", resize); resize();
    const animate = () => {
      const state = stateRef.current; const commands = state?.commands; const temperature = state?.sensors.temperatureC ?? 25; const pressure = state?.sensors.pressureMbar ?? 1013; const hot = commands?.heater ?? false; const vacuum = commands?.vacuumPump ?? false; const extracting = commands?.extractor ?? false; const condensing = commands?.condenser ?? false; const cooling = commands?.cooling ?? false; const fault = state?.interlocks.overTemperature ?? false; const time = frame++ / 60;
      const vacuumLevel = Math.max(0, Math.min(1, 1 - pressure / 1013.25)); const thermal = Math.max(0, Math.min(1, (temperature - 25) / 125));
      heaterRing.material.color.setHex(fault ? 0xef4444 : hot ? 0xf97316 : 0x334155); chamber.material.emissive.setHex(fault ? 0x5f1111 : hot ? 0x5a2108 : 0x07334a); ultrasonic.material.color.setHex(extracting ? 0xa78bfa : 0x334155); key.color.setHex(fault ? 0xef4444 : hot ? 0xfb923c : 0x22d3ee); key.intensity = hot ? 30 : 18; pumpRotor.rotation.x += vacuum ? 0.3 : 0.02; pumpRotor.material.color.setHex(vacuum ? 0x22d3ee : 0x334155);
      vacuumLineMaterial.color.setHex(vacuum ? 0x22d3ee : 0x164e63); vaporLineMaterial.color.setHex(extracting || condensing ? 0x38bdf8 : 0x155e75); coolingLineMaterial.color.setHex(cooling ? 0x60a5fa : 0x1e3a5f); powerCableMaterial.color.setHex(hot || vacuum || extracting || condensing || cooling ? 0xf59e0b : 0x334155);
      trapGroups.forEach((group, i) => { const data = state?.coldTraps?.[i]; const active = condensing || cooling; const temp = data?.temperatureC; const coldFactor = typeof temp === "number" ? Math.max(0, Math.min(1, (25 - temp) / 105)) : 0.35; trapBodies[i].material.emissive.setHex(active ? (coldFactor > 0.65 ? 0x082f49 : 0x10243a) : 0x061522); trapCoils[i].material.color.setHex(active ? (coldFactor > 0.65 ? 0x60a5fa : 0x38bdf8) : 0x2563eb); group.position.y = 3.25 + Math.sin(time * 0.5 + i) * 0.015; });
      chamberParticles.children.forEach((p, i) => { const offset = p.userData.offset as number; const travel = (time * (vacuum || extracting ? 0.09 : 0.015) + offset) % 1; p.position.set(-1.0 + travel * 1.9, -1.35 + ((i * 0.47) % 2.7), 0.4 + Math.sin(i * 1.7 + time) * 0.5); p.visible = vacuum || extracting || hot; p.scale.setScalar(0.45 + vacuumLevel * 1.2 + thermal * 0.7); });
      flowParticles.children.forEach((p, i) => { const offset = p.userData.offset as number; const active = vacuum || extracting || condensing || cooling; const curve = extracting || condensing ? vaporCurve : cooling ? coolingCurve : vacuumCurve; const travel = active ? (time * (vacuum ? 0.18 : 0.1) + offset) % 1 : 0; p.position.copy(active ? curve.getPointAt(travel) : new THREE.Vector3(0, -20, 0)); p.visible = active; p.scale.setScalar(active ? 0.7 + thermal * 0.5 : 0); const m = (p as THREE.Mesh).material as THREE.MeshBasicMaterial; m.color.setHex(cooling ? 0x60a5fa : vacuum ? 0x22d3ee : 0xfbbf24); if (i % 3 === 0 && condensing) p.scale.multiplyScalar(0.7); });
      reactor.rotation.y = Math.sin(time * 0.35) * 0.02; renderer.render(scene, camera); raf = requestAnimationFrame(animate);
    };
    animate(); return () => { cancelAnimationFrame(raf); window.removeEventListener("resize", resize); renderer.dispose(); mount.removeChild(renderer.domElement); };
  }, []);
  const stage = machine?.stage ?? "PRE_FLIGHT"; const fault = machine?.interlocks.overTemperature; const commands = machine?.commands; const hasEngineFrame = Boolean(machine); const traps = machine?.coldTraps ?? [];
  return <div className="relative h-[590px] overflow-hidden rounded-2xl border border-cyan-500/20 bg-slate-950/90 shadow-2xl shadow-cyan-950/20"><div ref={mountRef} className="absolute inset-0" />
    <div className="pointer-events-none absolute inset-x-0 top-0 flex items-start justify-between bg-gradient-to-b from-slate-950/95 via-slate-950/65 to-transparent p-4"><div><div className="flex items-center gap-2 font-mono text-[10px] font-semibold tracking-[0.25em] text-cyan-300"><span className={`h-2 w-2 rounded-full ${fault ? "bg-red-400" : hasEngineFrame ? "bg-emerald-400" : "bg-slate-500"}`} />3D PROCESS MACHINE</div><div className="mt-1 text-[10px] text-slate-500">LIVE ENGINE STATE → VISUAL PROCESS MODEL</div></div><div className={`rounded-lg border px-3 py-2 font-mono text-[9px] ${fault ? "border-red-500/30 bg-red-500/10 text-red-300" : hasEngineFrame ? "border-emerald-500/20 bg-emerald-500/5 text-emerald-300" : "border-slate-700 bg-slate-950/80 text-slate-500"}`}>{fault ? "SAFETY TRIP" : hasEngineFrame ? stage : "WAITING FOR ENGINE FRAME"}</div></div>
    <div className="pointer-events-none absolute left-4 top-20 space-y-1.5 font-mono text-[9px]"><div className="rounded bg-slate-950/70 px-2 py-1 text-slate-400">REACTOR</div><div className="rounded bg-slate-950/70 px-2 py-1 text-slate-400">VACUUM PUMP</div><div className="rounded bg-slate-950/70 px-2 py-1 text-slate-400">VAPOR / CONDENSATION</div></div>
    <div className="pointer-events-none absolute right-4 top-20 rounded-xl border border-white/10 bg-slate-950/80 p-3 font-mono text-[9px] shadow-xl backdrop-blur"><div className="mb-2 text-[8px] tracking-[0.2em] text-slate-500">LIVE CONNECTIONS</div><div className="space-y-1.5 text-slate-400"><div><span className={commands?.vacuumPump ? "text-cyan-300" : "text-slate-600"}>●</span> VACUUM LINE</div><div><span className={commands?.extractor || commands?.condenser ? "text-sky-300" : "text-slate-600"}>●</span> VAPOR LINE</div><div><span className={commands?.cooling ? "text-blue-300" : "text-slate-600"}>●</span> COOLING LINE</div><div><span className={commands?.heater ? "text-amber-300" : "text-slate-600"}>●</span> POWER / HEAT</div></div></div>
    <div className="absolute bottom-3 left-3 right-3 grid grid-cols-2 gap-2 md:grid-cols-6"><div className="rounded-lg border border-cyan-500/20 bg-slate-950/85 p-2 font-mono backdrop-blur"><div className="text-[8px] text-slate-500">REACTOR</div><div className="text-sm text-cyan-300">{machine ? `${machine.sensors.temperatureC.toFixed(1)} °C` : "—"}</div></div><div className="rounded-lg border border-cyan-500/20 bg-slate-950/85 p-2 font-mono backdrop-blur"><div className="text-[8px] text-slate-500">PRESSURE</div><div className="text-sm text-cyan-300">{machine ? `${machine.sensors.pressureMbar.toFixed(1)} mbar` : "—"}</div></div>{[0,1,2,3].map(i=><div key={i} className="rounded-lg border border-slate-800 bg-slate-950/85 p-2 font-mono backdrop-blur"><div className="text-[8px] text-slate-500">COLD TRAP {i+1}</div><div className="text-sm text-sky-300">{typeof traps[i]?.temperatureC === "number" ? `${traps[i].temperatureC.toFixed(1)} °C` : "—"}</div><div className="text-[8px] text-slate-500">CONDENSED {typeof traps[i]?.condensedWaterKg === "number" ? `${traps[i].condensedWaterKg.toFixed(3)} kg` : "—"}</div></div>)}</div>
  </div>;
}
