import { useEffect, useMemo, useRef, useState } from "react";
import { AlertTriangle, CheckCircle2, CircleGauge, Pause, Play, RotateCcw, Square, Thermometer, Wind, Zap } from "lucide-react";
import { Button } from "@/components/ui/button";
import { trpc } from "@/lib/trpc";
import { toast } from "sonner";

interface ProcessSimulatorProps { experimentId: string; onExit?: () => void; onComplete?: () => void; }
type Stage = "preflight" | "loading" | "evacuation" | "heating" | "extraction" | "condensation" | "cooling" | "complete";
interface Frame { timestamp: number; pressure: number; temperature: number; yieldPercentage: number; waterRemoved: number; oilRecovered: number; energyConsumed: number; efficiency: number; }
const STAGES: Array<{ id: Stage; label: string; description: string }> = [
  { id: "preflight", label: "PRE-FLIGHT", description: "Checking sensors, chamber seals and process interlocks" },
  { id: "loading", label: "CHARGE", description: "Loading botanical material and verifying mass balance" },
  { id: "evacuation", label: "VACUUM", description: "Evacuating the chamber toward the target pressure" },
  { id: "heating", label: "HEAT-UP", description: "Ramping temperature under controlled conditions" },
  { id: "extraction", label: "EXTRACTION", description: "Driving moisture and volatile compounds from the matrix" },
  { id: "condensation", label: "CONDENSATION", description: "Recovering vapor and separating condensate streams" },
  { id: "cooling", label: "COOL-DOWN", description: "Returning the chamber to a safe handling state" },
  { id: "complete", label: "COMPLETE", description: "Final mass and energy balance calculated" },
];
function stageForProgress(progress: number): Stage { if (progress >= .995) return "complete"; if (progress >= .90) return "cooling"; if (progress >= .78) return "condensation"; if (progress >= .45) return "extraction"; if (progress >= .25) return "heating"; if (progress >= .10) return "evacuation"; if (progress >= .04) return "loading"; return "preflight"; }
function Gauge({ label, value, max, unit, icon: Icon }: { label: string; value: number; max: number; unit: string; icon: typeof Wind }) { const percent = Math.max(0, Math.min(100, value / Math.max(max, .001) * 100)); return <div className="rounded-xl border border-cyan-500/20 bg-slate-900/70 p-4"><div className="mb-2 flex items-center gap-2 text-xs uppercase tracking-widest text-slate-400"><Icon className="h-4 w-4 text-cyan-400" />{label}</div><div className="flex items-end justify-between"><div className="font-mono text-2xl font-bold text-cyan-300">{value.toFixed(1)}</div><div className="text-xs text-slate-500">{unit}</div></div><div className="mt-3 h-1.5 overflow-hidden rounded-full bg-slate-800"><div className="h-full rounded-full bg-cyan-400 transition-all" style={{ width: `${percent}%` }} /></div></div>; }
export function ProcessSimulator({ experimentId, onExit, onComplete }: ProcessSimulatorProps) {
  const experimentQuery = trpc.experiments.get.useQuery(experimentId); const simulationMutation = trpc.simulation.run.useMutation();
  const [frames, setFrames] = useState<Frame[]>([]); const [cursor, setCursor] = useState(0); const [running, setRunning] = useState(false); const [paused, setPaused] = useState(false); const [alarm, setAlarm] = useState<string | null>(null); const timerRef = useRef<number | null>(null);
  const current = frames[cursor] ?? { timestamp: 0, pressure: 1013.25, temperature: 25, yieldPercentage: 0, waterRemoved: 0, oilRecovered: 0, energyConsumed: 0, efficiency: 0 }; const progress = frames.length > 1 ? cursor / (frames.length - 1) : 0; const activeStage = stageForProgress(progress); const stageIndex = STAGES.findIndex(s => s.id === activeStage); const recentFrames = useMemo(() => frames.slice(Math.max(0, cursor - 80), cursor + 1), [frames, cursor]);
  useEffect(() => { if (!running || paused || !frames.length) return; timerRef.current = window.setInterval(() => setCursor(v => { if (v >= frames.length - 1) { setRunning(false); onComplete?.(); return v; } return v + 1; }), 80); return () => { if (timerRef.current !== null) window.clearInterval(timerRef.current); }; }, [running, paused, frames.length, onComplete]);
  useEffect(() => () => { if (timerRef.current !== null) window.clearInterval(timerRef.current); }, []);
  const startSimulation = async () => { if (!experimentQuery.data) return; setAlarm(null); setCursor(0); const experiment = experimentQuery.data; const p = experiment.inputParameters as Record<string, unknown>; try { const result = await simulationMutation.mutateAsync({ experimentId, materialId: experiment.materialId, materialWeight: Number(p.materialWeight), waterContent: Number(p.waterContent), oilContent: Number(p.oilContent), targetPressure: Number(p.targetPressure), targetTemperature: Number(p.targetTemperature), ultrasonicFrequency: Number(p.ultrasonicFrequency), duration: Number(p.duration), materialWaterRatio: String(p.materialWaterRatio), processModel: p.processModel as "vacuum" | "distillation" | "ultrasonic" | "hybrid" }); setFrames((result.results?.realTimeData ?? []) as unknown as Frame[]); setRunning(true); setPaused(false); toast.success("Process simulation loaded — control room is live"); } catch (error) { console.error(error); setAlarm("SIMULATION ENGINE ERROR — PROCESS NOT STARTED"); toast.error("Simulation failed"); } };
  const reset = () => { setRunning(false); setPaused(false); setCursor(0); setFrames([]); setAlarm(null); };
  const chartPoints = recentFrames.map((f, i) => { const x = recentFrames.length <= 1 ? 0 : i / (recentFrames.length - 1) * 100; const y = 100 - Math.min(100, f.temperature / 150 * 100); return `${x},${y}`; }).join(" ");
  return <div className="min-h-screen bg-[radial-gradient(circle_at_top,#10263a_0%,#050912_45%,#02040a_100%)] p-4 text-slate-100 md:p-6"><div className="mx-auto max-w-[1500px] space-y-4">
    <header className="flex flex-col gap-3 rounded-2xl border border-cyan-500/20 bg-slate-950/70 p-5 backdrop-blur md:flex-row md:items-center md:justify-between"><div><div className="flex items-center gap-3"><div className={`h-3 w-3 rounded-full ${running && !paused ? "animate-pulse bg-emerald-400" : "bg-slate-600"}`} /><span className="font-mono text-xs tracking-[0.35em] text-cyan-400">IUVFES // DIGITAL TWIN CONTROL SYSTEM</span></div><h1 className="mt-2 text-2xl font-bold tracking-wide md:text-3xl">PROCESS SIMULATION CONTROL ROOM</h1><p className="font-mono text-xs text-slate-500">EXPERIMENT {experimentId}</p></div><div className="flex gap-2"><Button onClick={startSimulation} disabled={simulationMutation.isPending || running} className="bg-cyan-500 text-slate-950 hover:bg-cyan-400"><Play className="mr-2 h-4 w-4" />START</Button><Button onClick={() => setPaused(v => !v)} disabled={!running} variant="outline" className="border-yellow-500/40 bg-transparent text-yellow-300"><Pause className="mr-2 h-4 w-4" />{paused ? "RESUME" : "PAUSE"}</Button><Button onClick={reset} variant="outline" className="border-red-500/30 bg-transparent text-red-300"><RotateCcw className="mr-2 h-4 w-4" />RESET</Button><Button onClick={onExit} variant="outline" className="border-slate-700 bg-transparent text-slate-300"><Square className="mr-2 h-4 w-4" />EXIT</Button></div></header>
    <section className="rounded-2xl border border-cyan-500/20 bg-slate-950/60 p-4"><div className="mb-4 flex items-center justify-between"><div><p className="text-xs uppercase tracking-widest text-slate-500">Current process phase</p><h2 className="text-xl font-semibold text-cyan-300">{STAGES[stageIndex]?.label}</h2></div><div className="font-mono text-xs text-slate-500">{Math.round(progress * 100)}% PROCESS COMPLETE</div></div><div className="grid grid-cols-2 gap-2 md:grid-cols-4 xl:grid-cols-8">{STAGES.map((item, index) => <div key={item.id} className={`rounded-lg border p-3 transition-all ${index === stageIndex ? "border-cyan-400/70 bg-cyan-400/10" : index < stageIndex ? "border-emerald-500/30 bg-emerald-500/5" : "border-slate-800 bg-slate-900/40"}`}><div className="mb-2 flex items-center justify-between">{index < stageIndex ? <CheckCircle2 className="h-4 w-4 text-emerald-400" /> : index === stageIndex ? <CircleGauge className="h-4 w-4 animate-pulse text-cyan-400" /> : <div className="h-4 w-4 rounded-full border border-slate-700" />}<span className="font-mono text-[10px] text-slate-600">0{index + 1}</span></div><div className="text-[11px] font-semibold tracking-wider">{item.label}</div></div>)}</div><p className="mt-3 text-sm text-slate-400">{STAGES[stageIndex]?.description}</p></section>
    {alarm && <div className="flex items-center gap-3 rounded-xl border border-red-500/40 bg-red-500/10 p-4 text-red-300"><AlertTriangle className="h-5 w-5" />{alarm}</div>}
    <div className="grid gap-4 lg:grid-cols-4"><Gauge label="CHAMBER PRESSURE" value={current.pressure} max={1013.25} unit="mbar" icon={Wind} /><Gauge label="PROCESS TEMPERATURE" value={current.temperature} max={150} unit="°C" icon={Thermometer} /><Gauge label="RECOVERY YIELD" value={current.yieldPercentage} max={100} unit="%" icon={CircleGauge} /><Gauge label="ENERGY LOAD" value={current.energyConsumed} max={10} unit="kWh" icon={Zap} /></div>
    <div className="grid gap-4 lg:grid-cols-[1.4fr_1fr]"><section className="rounded-2xl border border-cyan-500/20 bg-slate-950/60 p-4"><div className="mb-3 flex items-center justify-between"><h3 className="font-semibold tracking-wider text-cyan-300">LIVE PROCESS TREND</h3><span className="font-mono text-xs text-slate-500">T: {current.timestamp}s</span></div><div className="relative h-64 overflow-hidden rounded-xl border border-slate-800 bg-slate-950"><div className="absolute inset-0 opacity-20" style={{ backgroundImage: "linear-gradient(rgba(34,211,238,.25) 1px, transparent 1px), linear-gradient(90deg, rgba(34,211,238,.25) 1px, transparent 1px)", backgroundSize: "40px 40px" }} />{chartPoints && <svg viewBox="0 0 100 100" preserveAspectRatio="none" className="absolute inset-0 h-full w-full p-5"><polyline points={chartPoints} fill="none" stroke="rgb(34 211 238)" strokeWidth="1.2" vectorEffect="non-scaling-stroke" /></svg>}<div className="absolute bottom-3 left-3 font-mono text-[10px] text-slate-600">TEMPERATURE PROFILE</div></div></section>
      <section className="rounded-2xl border border-cyan-500/20 bg-slate-950/60 p-4"><h3 className="mb-4 font-semibold tracking-wider text-cyan-300">MACHINE STATE</h3><div className="space-y-3 font-mono text-xs">{[["VACUUM PUMP", activeStage === "evacuation" ? "ACTIVE" : progress > .1 ? "STANDBY" : "OFF"],["HEATER", activeStage === "heating" || activeStage === "extraction" ? "RAMPING" : progress > .25 ? "HOLD" : "OFF"],["EXTRACTOR", activeStage === "extraction" ? "ACTIVE" : "STANDBY"],["CONDENSER", activeStage === "condensation" ? "ACTIVE" : progress > .78 ? "HOLD" : "STANDBY"],["INTERLOCK", "ARMED"],["MASS BALANCE", `${current.oilRecovered.toFixed(3)} kg oil / ${current.waterRemoved.toFixed(3)} kg water`]].map(([label, value]) => <div key={label} className="flex items-center justify-between rounded-lg border border-slate-800 bg-slate-900/50 p-3"><span className="text-slate-500">{label}</span><span className={value === "ACTIVE" || value === "RAMPING" ? "text-emerald-300" : "text-cyan-300"}>{value}</span></div>)}</div></section></div>
    <section className="rounded-2xl border border-cyan-500/20 bg-slate-950/60 p-4"><div className="grid gap-3 md:grid-cols-4"><div><span className="text-xs text-slate-500">OIL RECOVERED</span><div className="font-mono text-xl text-amber-300">{current.oilRecovered.toFixed(3)} kg</div></div><div><span className="text-xs text-slate-500">WATER REMOVED</span><div className="font-mono text-xl text-blue-300">{current.waterRemoved.toFixed(3)} kg</div></div><div><span className="text-xs text-slate-500">EFFICIENCY</span><div className="font-mono text-xl text-emerald-300">{current.efficiency.toFixed(2)}%</div></div><div><span className="text-xs text-slate-500">DATA FRAME</span><div className="font-mono text-xl text-cyan-300">{frames.length ? `${cursor + 1}/${frames.length}` : "READY"}</div></div></div></section>
  </div></div>;
}
