import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { AlertTriangle, CheckCircle2, FileText, Pause, Play, RotateCcw, Snowflake, Square, Thermometer, Wind, Zap } from "lucide-react";
import { Button } from "@/components/ui/button";
import { trpc } from "@/lib/trpc";
import { toast } from "sonner";
import { ProcessMachine3D } from "@/components/ProcessMachine3D";
import { ProcessEventTimeline } from "@/components/ProcessEventTimeline";
import { ScientificRunRecorder } from "@/components/ScientificRunRecorder";
import { LiveProcessTrend } from "@/components/LiveProcessTrend";
import { CausalFrameInspector } from "@/components/CausalFrameInspector";
import { ProcessRunReplay } from "@/components/ProcessRunReplay";
import { ReplayEvidence, type ReplayEvidenceFrame } from "@/components/ReplayEvidence";

type Stage = "PRE_FLIGHT" | "CHARGE" | "VACUUM" | "HEAT_UP" | "EXTRACTION" | "CONDENSATION" | "COOL_DOWN" | "COMPLETE" | "FAULT";
type Sensors = { chamberSealed: boolean; pressureMbar: number; temperatureC: number; yieldPercent: number; waterRemovedKg: number; oilRecoveredKg: number; energyKwh: number };
type Commands = { vacuumPump: boolean; heater: boolean; extractor: boolean; condenser: boolean; cooling: boolean };
type Frame = {
  step:number; timestampSeconds:number; sensorBefore:Sensors;
  controller:{stage:Stage;progress:number;elapsedSeconds:number;sensors:Sensors;commands:Commands;interlocks:{chamberSealed:boolean;pressureSafeForHeating:boolean;temperatureSafeForCooling:boolean;overTemperature:boolean;vacuumAchieved:boolean;allSystemsSafe:boolean};alarm:string|null;transitionReason:string};
  controlOutput:{heaterPower:number;vacuumPumpPower:number;valve:{vacuumIsolation:number;vaporToCondenser:number;coolingWater:number}};
  intendedCommands:Commands; effectiveCommands:Commands; physicalSensorAfter:Sensors; sensorAfter:Sensors; materialInventory:any;
  safety:{stage:Stage;allSystemsSafe:boolean;chamberSealed:boolean;pressureSafeForHeating:boolean;temperatureSafeForCooling:boolean;overTemperature:boolean;vacuumAchieved:boolean;alarm:string|null;transitionReason:string}; paused:boolean;
  ultrasonic?:{effectiveFrequencyKHz?:number;effectivePowerKW?:number;powerDensityWPerL?:number;status?:string};
  hardwareDiagnostics?:{connectedVolumeL?:number;pipeVolumeL?:number;vacuumConductanceM3h?:number|null;effectivePumpCapacityM3h?:number;ultrasonicEffectivePowerKw?:number;ultrasonicPowerDensityWPerL?:number;hardwareWarnings?:string[];coldTrapTemperaturesC?:number[];coldTrapHeatLoadKw?:number;coldTrapCondensationCapacityKgPerSecond?:number;coldTrapStageCondensedWaterKg?:number[]};
};
const STAGES:Stage[]=["PRE_FLIGHT","CHARGE","VACUUM","HEAT_UP","EXTRACTION","CONDENSATION","COOL_DOWN","COMPLETE","FAULT"];
function Slider({label,value,min,max,step,unit,Icon,onChange,onApply,disabled}:{label:string;value:number;min:number;max:number;step:number;unit:string;Icon:any;onChange:(v:number)=>void;onApply:()=>void;disabled?:boolean}){return <div className="rounded-xl border border-cyan-500/20 bg-slate-900/70 p-3"><div className="flex items-center justify-between text-[10px] uppercase tracking-[0.18em] text-slate-500"><span className="flex items-center gap-2"><Icon className="h-4 w-4 text-cyan-400"/>{label}</span><span className="font-mono text-cyan-300">{value.toFixed(step<1?1:0)} {unit}</span></div><input disabled={disabled} className="mt-3 w-full accent-cyan-400 disabled:opacity-40" type="range" min={min} max={max} step={step} value={value} onChange={e=>onChange(Number(e.target.value))} onPointerUp={onApply}/><div className="mt-2 flex justify-between text-[9px] font-mono text-slate-600"><span>{min}</span><span>{max}</span></div></div>}
function Metric({label,value,accent="cyan"}:{label:string;value:string;accent?:"cyan"|"sky"|"amber"|"emerald"}){const text={cyan:"text-cyan-300",sky:"text-sky-300",amber:"text-amber-300",emerald:"text-emerald-300"}[accent];return <div className="rounded-xl border border-slate-800 bg-slate-950/75 p-3"><div className="text-[9px] tracking-[0.2em] text-slate-500">{label}</div><div className={`mt-1 font-mono text-lg ${text}`}>{value}</div></div>}
function fmt(v:unknown,d=3){return typeof v==="number"&&Number.isFinite(v)?v.toFixed(d):"—"}

export function ProcessSimulator({experimentId,onExit,onComplete}:{experimentId:string;onExit?:()=>void;onComplete?:()=>void}){
 const experiment=trpc.experiments.get.useQuery(experimentId);
 const create=trpc.closedLoop.create.useMutation(),start=trpc.closedLoop.start.useMutation(),step=trpc.closedLoop.step.useMutation(),control=trpc.closedLoop.control.useMutation(),pause=trpc.closedLoop.pause.useMutation(),resume=trpc.closedLoop.resume.useMutation(),stop=trpc.closedLoop.stop.useMutation(),reset=trpc.closedLoop.reset.useMutation();
 const [sessionId,setSessionId]=useState<string|null>(null),[frames,setFrames]=useState<Frame[]>([]),[running,setRunning]=useState(false),[paused,setPaused]=useState(false),[completed,setCompleted]=useState(false);
 const [replayMode,setReplayMode]=useState(false),[replayIndex,setReplayIndex]=useState(0);
 const [temperature,setTemperature]=useState(62),[pressure,setPressure]=useState(20),[cooling,setCooling]=useState(35),[heaterLimit,setHeaterLimit]=useState(1),[pumpLimit,setPumpLimit]=useState(1),[condenserLimit,setCondenserLimit]=useState(1),[coolingLimit,setCoolingLimit]=useState(1);
 const busy=useRef(false),timer=useRef<number|null>(null),scientificOutputRef=useRef<HTMLDivElement|null>(null);const clearTimer=()=>{if(timer.current!==null)window.clearInterval(timer.current);timer.current=null};useEffect(()=>()=>clearTimer(),[]);
 const latest=frames.at(-1),liveSensor=latest?.sensorAfter,liveState=latest?.controller,liveSafety=latest?.safety;
 const displayIndex=replayMode?Math.min(replayIndex,Math.max(0,frames.length-1)):Math.max(0,frames.length-1);
 const displayFrame=frames.length?frames[displayIndex]:undefined;
 const sensor=displayFrame?.sensorAfter,state=displayFrame?.controller,output=displayFrame?.controlOutput,safety=displayFrame?.safety;
 const recent=useMemo(()=>replayMode?frames.slice(0,displayIndex+1).slice(-80):frames.slice(-80),[frames,replayMode,displayIndex]);
 const replayFrames=useMemo(()=>replayMode?frames.slice(0,displayIndex+1):frames,[frames,replayMode,displayIndex]);
 const onReplayFrame=useCallback((frame:Frame|undefined,index:number)=>{if(!frame)return;setReplayMode(true);setReplayIndex(index)},[]);
 const oneStep=async(id:string)=>{if(busy.current)return;busy.current=true;try{const result=await step.mutateAsync(id);if(result.frame){const frame=result.frame as Frame;setFrames(prev=>[...prev,frame]);setReplayMode(false);if(frame.safety.stage==="COMPLETE"){setRunning(false);setCompleted(true);clearTimer();onComplete?.()}if(frame.safety.stage==="FAULT"){setRunning(false);clearTimer();toast.error(frame.safety.alarm??"Safety fault")}}}catch(e){console.error(e);setRunning(false);clearTimer();toast.error("Live step failed")}finally{busy.current=false}};
 useEffect(()=>{clearTimer();if(!running||paused||!sessionId)return;timer.current=window.setInterval(()=>void oneStep(sessionId),1000);return clearTimer},[running,paused,sessionId]);
 const startSimulation=async()=>{if(!experiment.data)return;const p=experiment.data.inputParameters as Record<string,unknown>;try{clearTimer();setFrames([]);setReplayMode(false);setReplayIndex(0);setCompleted(false);setPaused(false);const hours=Number(p.duration),maxSteps=Math.max(1,Math.min(100000,Math.ceil(Number.isFinite(hours)&&hours>0?hours*3600:300)));const created=await create.mutateAsync({experimentId,materialWeight:Number(p.materialWeight),waterContent:Number(p.waterContent),oilContent:Number(p.oilContent),targetPressure:pressure,targetTemperature:temperature,coolingTemperature:cooling,dtSeconds:1,maxSteps});await start.mutateAsync(created.sessionId);setSessionId(created.sessionId);setRunning(true);await oneStep(created.sessionId);toast.success("Closed-loop engine connected")}catch(e){console.error(e);toast.error("Could not start closed-loop controller")}};
 const apply=async()=>{if(!sessionId)return;try{const view=await control.mutateAsync({sessionId,targetPressureMbar:pressure,targetTemperatureC:temperature,coolingTemperatureC:cooling,heaterMax:heaterLimit,vacuumPumpMax:pumpLimit,condenserMax:condenserLimit,coolingMax:coolingLimit,operatorNotes:"Operator live controller adjustment."});setTemperature(view.targets.targetTemperatureC);setPressure(view.targets.targetPressureMbar);setCooling(view.targets.coolingTemperatureC);setHeaterLimit(view.operatorLimits.heaterMax);setPumpLimit(view.operatorLimits.vacuumPumpMax);setCondenserLimit(view.operatorLimits.condenserMax);setCoolingLimit(view.operatorLimits.coolingMax);toast.success("Controller settings applied")}catch{toast.error("Controller setting rejected")}};
 const doPause=async()=>{if(!sessionId)return;try{await pause.mutateAsync(sessionId);clearTimer();setPaused(true);setRunning(false)}catch{toast.error("Pause rejected")}};const doResume=async()=>{if(!sessionId)return;try{await resume.mutateAsync(sessionId);setPaused(false);setRunning(true);setReplayMode(false)}catch{toast.error("Resume rejected")}};const doStop=async()=>{if(!sessionId)return;try{await stop.mutateAsync(sessionId);clearTimer();setRunning(false);setPaused(false)}catch{toast.error("Stop rejected")}};const doReset=async()=>{clearTimer();if(sessionId)try{await reset.mutateAsync(sessionId)}catch{}setSessionId(null);setFrames([]);setReplayMode(false);setReplayIndex(0);setRunning(false);setPaused(false);setCompleted(false)};
 const machine=displayFrame?{stage:displayFrame.safety.stage,commands:displayFrame.effectiveCommands,sensors:{pressureMbar:displayFrame.sensorAfter.pressureMbar,temperatureC:displayFrame.sensorAfter.temperatureC},interlocks:{vacuumAchieved:displayFrame.safety.vacuumAchieved,overTemperature:displayFrame.safety.overTemperature},coldTraps:(displayFrame.hardwareDiagnostics?.coldTrapTemperaturesC??[]).map((temperatureC,i)=>({temperatureC,condensedWaterKg:displayFrame.hardwareDiagnostics?.coldTrapStageCondensedWaterKg?.[i]}))}:undefined;
 const disabled=!running||replayMode;
 const evidenceFrames=frames as unknown as ReplayEvidenceFrame[];
 return <div className="min-h-screen bg-[radial-gradient(circle_at_top,#10263a_0%,#050912_45%,#02040a_100%)] p-4 text-slate-100 md:p-6"><div className="mx-auto max-w-[1550px] space-y-4">
  <header className="flex flex-col gap-4 rounded-2xl border border-cyan-500/20 bg-slate-950/80 p-5 md:flex-row md:items-center md:justify-between"><div><div className="font-mono text-xs tracking-[0.3em] text-cyan-400">IUVFES // DIGITAL TWIN</div><h1 className="mt-2 text-2xl font-bold">PROCESS SIMULATOR</h1><p className="font-mono text-xs text-slate-500">{replayMode?"RUN REPLAY": "LIVE CLOSED-LOOP"} · {sessionId?`SESSION ${sessionId.slice(0,8)}`:"NOT CONNECTED"}</p></div><div className="flex flex-wrap gap-2"><Button onClick={()=>scientificOutputRef.current?.scrollIntoView({behavior:"smooth"})} disabled={!frames.length} variant="outline" className="border-emerald-500/40 text-emerald-300"><FileText className="mr-2 h-4 w-4"/>RESULTS / PRINT</Button><Button onClick={()=>void startSimulation()} disabled={running||paused||create.isPending||start.isPending} className="bg-cyan-500 text-slate-950"><Play className="mr-2 h-4 w-4"/>START</Button><Button onClick={()=>void(paused?doResume():doPause())} disabled={!running&&!paused} variant="outline" className="border-yellow-500/40 text-yellow-300">{paused?<Play className="mr-2 h-4 w-4"/>:<Pause className="mr-2 h-4 w-4"/>}{paused?"RESUME":"PAUSE"}</Button><Button onClick={()=>void doStop()} disabled={!sessionId} variant="outline" className="border-red-500/40 text-red-300"><Square className="mr-2 h-4 w-4"/>STOP</Button><Button onClick={()=>void doReset()} variant="outline"><RotateCcw className="mr-2 h-4 w-4"/>RESET</Button>{onExit&&<Button onClick={onExit} variant="outline">EXIT</Button>}</div></header>
  <section className="grid gap-3 lg:grid-cols-3"><Slider label="CONTROL SUHU" value={temperature} min={30} max={100} step={0.5} unit="°C" Icon={Thermometer} onChange={setTemperature} onApply={()=>void apply()} disabled={disabled}/><Slider label="CONTROL VAKUM" value={pressure} min={5} max={500} step={1} unit="mbar" Icon={Wind} onChange={setPressure} onApply={()=>void apply()} disabled={disabled}/><Slider label="TARGET COOL-DOWN" value={cooling} min={25} max={70} step={0.5} unit="°C" Icon={Snowflake} onChange={setCooling} onApply={()=>void apply()} disabled={disabled}/></section>
  <section className="grid gap-3 md:grid-cols-2 xl:grid-cols-4"><Slider label="HEATER LIMIT" value={heaterLimit*100} min={0} max={100} step={1} unit="%" Icon={Zap} onChange={v=>setHeaterLimit(v/100)} onApply={()=>void apply()} disabled={disabled}/><Slider label="VACUUM PUMP LIMIT" value={pumpLimit*100} min={0} max={100} step={1} unit="%" Icon={Wind} onChange={v=>setPumpLimit(v/100)} onApply={()=>void apply()} disabled={disabled}/><Slider label="CONDENSER LIMIT" value={condenserLimit*100} min={0} max={100} step={1} unit="%" Icon={Snowflake} onChange={v=>setCondenserLimit(v/100)} onApply={()=>void apply()} disabled={disabled}/><Slider label="COOLING LIMIT" value={coolingLimit*100} min={0} max={100} step={1} unit="%" Icon={Snowflake} onChange={v=>setCoolingLimit(v/100)} onApply={()=>void apply()} disabled={disabled}/></section>
  <section className="grid gap-3 md:grid-cols-2 xl:grid-cols-6"><Metric label="TEMPERATURE" value={sensor?`${fmt(sensor.temperatureC,1)} °C`:"—"}/><Metric label="PRESSURE" value={sensor?`${fmt(sensor.pressureMbar,1)} mbar`:"—"}/><Metric label="YIELD" value={sensor?`${fmt(sensor.yieldPercent,2)} %`:"—"} accent="emerald"/><Metric label="OIL RECOVERED" value={sensor?`${fmt(sensor.oilRecoveredKg,3)} kg`:"—"} accent="amber"/><Metric label="WATER REMOVED" value={sensor?`${fmt(sensor.waterRemovedKg,3)} kg`:"—"} accent="sky"/><Metric label="ENERGY" value={sensor?`${fmt(sensor.energyKwh,3)} kWh`:"—"} accent="amber"/></section>
  <section className="rounded-2xl border border-cyan-500/20 bg-slate-950/70 p-3"><ProcessMachine3D machine={machine}/></section>
  {frames.length>0&&<ProcessRunReplay frames={frames} onFrameChange={onReplayFrame}/>} 
  {frames.length>0&&<ReplayEvidence experimentId={experimentId} sessionId={sessionId} frames={evidenceFrames} selectedIndex={displayIndex} onSelectIndex={(index)=>onReplayFrame(frames[index],index)}/>} 
  <LiveProcessTrend frames={recent}/>
  <CausalFrameInspector frames={replayFrames}/>
  <section className="grid gap-4 xl:grid-cols-2"><ProcessEventTimeline timeline={replayFrames.map(f=>({stage:f.safety.stage,elapsedSeconds:f.controller.elapsedSeconds,alarm:f.safety.alarm,transitionReason:f.safety.transitionReason,interlocks:{overTemperature:f.safety.overTemperature,vacuumAchieved:f.safety.vacuumAchieved,allSystemsSafe:f.safety.allSystemsSafe}}))}/><div className="rounded-2xl border border-cyan-500/20 bg-slate-950/70 p-4"><div className="mb-3 flex items-center justify-between"><h3 className="font-semibold tracking-wider text-cyan-300">PROCESS STATUS</h3><span className={`font-mono text-[10px] ${safety?.allSystemsSafe?"text-emerald-300":"text-red-300"}`}>{safety?.allSystemsSafe?"● ALL SYSTEMS SAFE":"● CHECK SAFETY"}</span></div><div className="grid grid-cols-2 gap-2 text-xs font-mono">{STAGES.map((s,i)=>{const current=state?.stage===s,done=state&&STAGES.indexOf(state.stage)>i;return <div key={s} className={`rounded-lg border p-2 ${current?"border-cyan-400/50 bg-cyan-400/10 text-cyan-300":done?"border-emerald-500/20 text-emerald-300":"border-slate-800 text-slate-600"}`}>{done?<CheckCircle2 className="inline h-3 w-3 mr-1"/>:current?<Zap className="inline h-3 w-3 mr-1"/>:null}{s}</div>})}</div>{safety?.alarm&&<div className="mt-3 rounded-lg border border-red-500/30 bg-red-500/10 p-3 text-xs text-red-300"><AlertTriangle className="mr-2 inline h-4 w-4"/>{safety.alarm}</div>}<div className="mt-3 text-[10px] text-slate-500">{safety?.transitionReason??"Waiting for engine frame."}</div></div></section>
  <div ref={scientificOutputRef}><ScientificRunRecorder experimentId={experimentId} frames={frames} completed={completed}/></div>
 </div></div>
}